copy "%CONFIGHOME%\dotfiles\.ctags" "%USERPROFILE%"
copy "%CONFIGHOME%\dotfiles\.gitconfig" "%USERPROFILE%"
copy "%CONFIGHOME%\dotfiles\.hgrc" "%USERPROFILE%"
copy "%CONFIGHOME%\setup\.vimrc" "%USERPROFILE%"

md "%USERPROFILE%\.config_storage"
md "%USERPROFILE%\.config_storage\vim"
md "%USERPROFILE%\.config_storage\vim\backup"
md "%USERPROFILE%\.config_storage\vim\sessions"
md "%USERPROFILE%\.config_storage\vim\undo"
